server:
  port: 0

spring:
  application:
    name: kafka-product-microservice

  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery:
          timeout:
            ms: 10000
        linger:
          ms: 5000
        request:
          timeout:
            ms: 5000
        enable:
          idempotence: true
        max:
          in:
            flight:
              requests:
                per:
                  connection: 5

#      retries: 10
#      properties:
#        retry:
#          backoff:
#            ms: 1000
